# -*- coding: utf-8 -*-
"""441. Arranging Coins.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dFlk8C3Tu5iMXM5eD7GEDlm5v-dge7TP
"""

class Solution(object):
    def arrangeCoins(self, n):
        nrows=0
        while n>=0:
            nrows=nrows+1
            n=n-nrows
        return nrows-1