# -*- coding: utf-8 -*-
"""plus one.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MRIzKFYwbH6DKn146cIFL0eVx08Hnk3v
"""

class Solution(object):
    def plusOne(self, digits):
        n = len(digits)

        # Traverse from the last digit backwards
        for i in range(n - 1, -1, -1):
            if digits[i] < 9:
                digits[i] += 1
                return digits
            digits[i] = 0  # since it was 9

        # If all digits are 9
        return [1] + digits

