# -*- coding: utf-8 -*-
"""69. Sqrt(x).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J6qUReWCphlWiu7wYU7uTrJ5gzHR7Bu4
"""

class Solution(object):
    def mySqrt(self, x):
        if x < 2:
            return x

        left, right = 1, x // 2

        while left <= right:
            mid = (left + right) // 2
            sq = mid * mid

            if sq == x:
                return mid
            elif sq < x:
                left = mid + 1
            else:
                right = mid - 1

        return right