# -*- coding: utf-8 -*-
"""13. RomanToInteger.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16UzxBrGS_Inl3Y7DJXO5ToO3f-Fo01qz
"""

class Solution(object):
    def romanToInt(self, s):
        roman = {
            'I': 1,
            'V': 5,
            'X': 10,
            'L': 50,
            'C': 100,
            'D': 500,
            'M': 1000
        }

        total = 0
        i = 0

        while i < len(s):
            # subtractive case (e.g. IV, IX, XL, XC, CD, CM)
            if i + 1 < len(s) and roman[s[i]] < roman[s[i+1]]:
                total += roman[s[i+1]] - roman[s[i]]
                i += 2
            else:
                total += roman[s[i]]
                i += 1

        return total

