# -*- coding: utf-8 -*-
"""Length of last word.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zaB5VSkBdm9eVx0d38M-Wq1sHp8kL2Yw
"""

class Solution(object):
    def lengthOfLastWord(self, s):
        word="Hello world"
        for i in s.split():
            length=len(i)
        return length