# -*- coding: utf-8 -*-
"""70. Climbing Stairs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iw9uZOfZQYQZLcw_VTriqdBsaihqKyNX
"""

class Solution(object):
    def climbStairs(self, n):
        if n <= 2:
            return n

        a, b = 1, 2   # ways(1), ways(2)
        for _ in range(3, n+1):
         a, b = b, a + b   # update

        return b