# -*- coding: utf-8 -*-
"""242. Valid Anagram.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fWzhntXt1jsBJI1RMxKgdb8SUzvciOTg
"""

class Solution(object):
    def isAnagram(self, s, t):
        if sorted(s)==sorted(t):
            return True
        else:
            return False