# -*- coding: utf-8 -*-
"""3110. Score of a String.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-NUCdehv5VZkyj6myTR-uLnktpY7oKp-
"""

class Solution(object):
    def scoreOfString(self, s):
        sum=0
        difference=0
        arr=[]
        for i in s:
            arr.append(ord(i))
        print(arr)
        for x in range(len(arr)-1):
            difference=max(arr[x],arr[x+1])-min(arr[x],arr[x+1])
            sum=sum+difference
        return sum