# -*- coding: utf-8 -*-
"""414. Third Maximum Number.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VDdBFiQY8YqA79_Kre7YwYaBrspvLvYG
"""

class Solution(object):
    def thirdMax(self, nums):
        sortarr=list(dict.fromkeys(nums))
        sortarr=sorted(sortarr, reverse=True)
        if len(sortarr)>=3:
            return sortarr[2]
        else:
            return sortarr[0]