# -*- coding: utf-8 -*-
"""20. Valid Paranthesis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jXzm-poI1mnuyz-tJQb7rtZ_jSVe1S8E
"""

class Solution(object):
    def isValid(self, s):
        stack = []
        pairs = {')':'(', '}':'{', ']':'['}

        for ch in s:
            if ch in "([{":
                stack.append(ch)
            else:
                if not stack or stack[-1] != pairs[ch]:
                    return False
                stack.pop()

        return len(stack) == 0